// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_precompile.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_5fprecompile_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_5fprecompile_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "proto_basic.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_5fprecompile_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_5fprecompile_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_5fprecompile_2eproto;
namespace top {
namespace evm_engine {
namespace precompile {
class ContractBridgeArgs;
class ContractBridgeArgsDefaultTypeInternal;
extern ContractBridgeArgsDefaultTypeInternal _ContractBridgeArgs_default_instance_;
class ContractContext;
class ContractContextDefaultTypeInternal;
extern ContractContextDefaultTypeInternal _ContractContext_default_instance_;
class PrecompileFailure;
class PrecompileFailureDefaultTypeInternal;
extern PrecompileFailureDefaultTypeInternal _PrecompileFailure_default_instance_;
class PrecompileOutput;
class PrecompileOutputDefaultTypeInternal;
extern PrecompileOutputDefaultTypeInternal _PrecompileOutput_default_instance_;
}  // namespace precompile
}  // namespace evm_engine
}  // namespace top
PROTOBUF_NAMESPACE_OPEN
template<> ::top::evm_engine::precompile::ContractBridgeArgs* Arena::CreateMaybeMessage<::top::evm_engine::precompile::ContractBridgeArgs>(Arena*);
template<> ::top::evm_engine::precompile::ContractContext* Arena::CreateMaybeMessage<::top::evm_engine::precompile::ContractContext>(Arena*);
template<> ::top::evm_engine::precompile::PrecompileFailure* Arena::CreateMaybeMessage<::top::evm_engine::precompile::PrecompileFailure>(Arena*);
template<> ::top::evm_engine::precompile::PrecompileOutput* Arena::CreateMaybeMessage<::top::evm_engine::precompile::PrecompileOutput>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace top {
namespace evm_engine {
namespace precompile {

// ===================================================================

class PrecompileOutput PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:top.evm_engine.precompile.PrecompileOutput) */ {
 public:
  inline PrecompileOutput() : PrecompileOutput(nullptr) {};
  virtual ~PrecompileOutput();

  PrecompileOutput(const PrecompileOutput& from);
  PrecompileOutput(PrecompileOutput&& from) noexcept
    : PrecompileOutput() {
    *this = ::std::move(from);
  }

  inline PrecompileOutput& operator=(const PrecompileOutput& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrecompileOutput& operator=(PrecompileOutput&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PrecompileOutput& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PrecompileOutput* internal_default_instance() {
    return reinterpret_cast<const PrecompileOutput*>(
               &_PrecompileOutput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PrecompileOutput& a, PrecompileOutput& b) {
    a.Swap(&b);
  }
  inline void Swap(PrecompileOutput* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrecompileOutput* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PrecompileOutput* New() const final {
    return CreateMaybeMessage<PrecompileOutput>(nullptr);
  }

  PrecompileOutput* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PrecompileOutput>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PrecompileOutput& from);
  void MergeFrom(const PrecompileOutput& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrecompileOutput* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "top.evm_engine.precompile.PrecompileOutput";
  }
  protected:
  explicit PrecompileOutput(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_5fprecompile_2eproto);
    return ::descriptor_table_proto_5fprecompile_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLogsFieldNumber = 4,
    kOutputFieldNumber = 3,
    kCostFieldNumber = 2,
    kExitStatusFieldNumber = 1,
  };
  // repeated .top.evm_engine.basic.ResultLog logs = 4;
  int logs_size() const;
  private:
  int _internal_logs_size() const;
  public:
  void clear_logs();
  ::top::evm_engine::basic::ResultLog* mutable_logs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::top::evm_engine::basic::ResultLog >*
      mutable_logs();
  private:
  const ::top::evm_engine::basic::ResultLog& _internal_logs(int index) const;
  ::top::evm_engine::basic::ResultLog* _internal_add_logs();
  public:
  const ::top::evm_engine::basic::ResultLog& logs(int index) const;
  ::top::evm_engine::basic::ResultLog* add_logs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::top::evm_engine::basic::ResultLog >&
      logs() const;

  // bytes output = 3;
  void clear_output();
  const std::string& output() const;
  void set_output(const std::string& value);
  void set_output(std::string&& value);
  void set_output(const char* value);
  void set_output(const void* value, size_t size);
  std::string* mutable_output();
  std::string* release_output();
  void set_allocated_output(std::string* output);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_output();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_output(
      std::string* output);
  private:
  const std::string& _internal_output() const;
  void _internal_set_output(const std::string& value);
  std::string* _internal_mutable_output();
  public:

  // uint64 cost = 2;
  void clear_cost();
  ::PROTOBUF_NAMESPACE_ID::uint64 cost() const;
  void set_cost(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_cost() const;
  void _internal_set_cost(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 exit_status = 1;
  void clear_exit_status();
  ::PROTOBUF_NAMESPACE_ID::uint32 exit_status() const;
  void set_exit_status(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_exit_status() const;
  void _internal_set_exit_status(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:top.evm_engine.precompile.PrecompileOutput)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::top::evm_engine::basic::ResultLog > logs_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr output_;
  ::PROTOBUF_NAMESPACE_ID::uint64 cost_;
  ::PROTOBUF_NAMESPACE_ID::uint32 exit_status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_5fprecompile_2eproto;
};
// -------------------------------------------------------------------

class PrecompileFailure PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:top.evm_engine.precompile.PrecompileFailure) */ {
 public:
  inline PrecompileFailure() : PrecompileFailure(nullptr) {};
  virtual ~PrecompileFailure();

  PrecompileFailure(const PrecompileFailure& from);
  PrecompileFailure(PrecompileFailure&& from) noexcept
    : PrecompileFailure() {
    *this = ::std::move(from);
  }

  inline PrecompileFailure& operator=(const PrecompileFailure& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrecompileFailure& operator=(PrecompileFailure&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PrecompileFailure& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PrecompileFailure* internal_default_instance() {
    return reinterpret_cast<const PrecompileFailure*>(
               &_PrecompileFailure_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PrecompileFailure& a, PrecompileFailure& b) {
    a.Swap(&b);
  }
  inline void Swap(PrecompileFailure* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrecompileFailure* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PrecompileFailure* New() const final {
    return CreateMaybeMessage<PrecompileFailure>(nullptr);
  }

  PrecompileFailure* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PrecompileFailure>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PrecompileFailure& from);
  void MergeFrom(const PrecompileFailure& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrecompileFailure* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "top.evm_engine.precompile.PrecompileFailure";
  }
  protected:
  explicit PrecompileFailure(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_5fprecompile_2eproto);
    return ::descriptor_table_proto_5fprecompile_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOutputFieldNumber = 3,
    kFailStatusFieldNumber = 1,
    kMinorStatusFieldNumber = 2,
    kCostFieldNumber = 4,
  };
  // bytes output = 3;
  void clear_output();
  const std::string& output() const;
  void set_output(const std::string& value);
  void set_output(std::string&& value);
  void set_output(const char* value);
  void set_output(const void* value, size_t size);
  std::string* mutable_output();
  std::string* release_output();
  void set_allocated_output(std::string* output);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_output();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_output(
      std::string* output);
  private:
  const std::string& _internal_output() const;
  void _internal_set_output(const std::string& value);
  std::string* _internal_mutable_output();
  public:

  // uint32 fail_status = 1;
  void clear_fail_status();
  ::PROTOBUF_NAMESPACE_ID::uint32 fail_status() const;
  void set_fail_status(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_fail_status() const;
  void _internal_set_fail_status(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 minor_status = 2;
  void clear_minor_status();
  ::PROTOBUF_NAMESPACE_ID::uint32 minor_status() const;
  void set_minor_status(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_minor_status() const;
  void _internal_set_minor_status(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint64 cost = 4;
  void clear_cost();
  ::PROTOBUF_NAMESPACE_ID::uint64 cost() const;
  void set_cost(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_cost() const;
  void _internal_set_cost(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:top.evm_engine.precompile.PrecompileFailure)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr output_;
  ::PROTOBUF_NAMESPACE_ID::uint32 fail_status_;
  ::PROTOBUF_NAMESPACE_ID::uint32 minor_status_;
  ::PROTOBUF_NAMESPACE_ID::uint64 cost_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_5fprecompile_2eproto;
};
// -------------------------------------------------------------------

class ContractContext PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:top.evm_engine.precompile.ContractContext) */ {
 public:
  inline ContractContext() : ContractContext(nullptr) {};
  virtual ~ContractContext();

  ContractContext(const ContractContext& from);
  ContractContext(ContractContext&& from) noexcept
    : ContractContext() {
    *this = ::std::move(from);
  }

  inline ContractContext& operator=(const ContractContext& from) {
    CopyFrom(from);
    return *this;
  }
  inline ContractContext& operator=(ContractContext&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ContractContext& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ContractContext* internal_default_instance() {
    return reinterpret_cast<const ContractContext*>(
               &_ContractContext_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ContractContext& a, ContractContext& b) {
    a.Swap(&b);
  }
  inline void Swap(ContractContext* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ContractContext* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ContractContext* New() const final {
    return CreateMaybeMessage<ContractContext>(nullptr);
  }

  ContractContext* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ContractContext>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ContractContext& from);
  void MergeFrom(const ContractContext& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ContractContext* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "top.evm_engine.precompile.ContractContext";
  }
  protected:
  explicit ContractContext(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_5fprecompile_2eproto);
    return ::descriptor_table_proto_5fprecompile_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAddressFieldNumber = 1,
    kCallerFieldNumber = 2,
    kApparentValueFieldNumber = 3,
  };
  // .top.evm_engine.basic.ProtoAddress address = 1;
  bool has_address() const;
  private:
  bool _internal_has_address() const;
  public:
  void clear_address();
  const ::top::evm_engine::basic::ProtoAddress& address() const;
  ::top::evm_engine::basic::ProtoAddress* release_address();
  ::top::evm_engine::basic::ProtoAddress* mutable_address();
  void set_allocated_address(::top::evm_engine::basic::ProtoAddress* address);
  private:
  const ::top::evm_engine::basic::ProtoAddress& _internal_address() const;
  ::top::evm_engine::basic::ProtoAddress* _internal_mutable_address();
  public:
  void unsafe_arena_set_allocated_address(
      ::top::evm_engine::basic::ProtoAddress* address);
  ::top::evm_engine::basic::ProtoAddress* unsafe_arena_release_address();

  // .top.evm_engine.basic.ProtoAddress caller = 2;
  bool has_caller() const;
  private:
  bool _internal_has_caller() const;
  public:
  void clear_caller();
  const ::top::evm_engine::basic::ProtoAddress& caller() const;
  ::top::evm_engine::basic::ProtoAddress* release_caller();
  ::top::evm_engine::basic::ProtoAddress* mutable_caller();
  void set_allocated_caller(::top::evm_engine::basic::ProtoAddress* caller);
  private:
  const ::top::evm_engine::basic::ProtoAddress& _internal_caller() const;
  ::top::evm_engine::basic::ProtoAddress* _internal_mutable_caller();
  public:
  void unsafe_arena_set_allocated_caller(
      ::top::evm_engine::basic::ProtoAddress* caller);
  ::top::evm_engine::basic::ProtoAddress* unsafe_arena_release_caller();

  // .top.evm_engine.basic.WeiU256 apparent_value = 3;
  bool has_apparent_value() const;
  private:
  bool _internal_has_apparent_value() const;
  public:
  void clear_apparent_value();
  const ::top::evm_engine::basic::WeiU256& apparent_value() const;
  ::top::evm_engine::basic::WeiU256* release_apparent_value();
  ::top::evm_engine::basic::WeiU256* mutable_apparent_value();
  void set_allocated_apparent_value(::top::evm_engine::basic::WeiU256* apparent_value);
  private:
  const ::top::evm_engine::basic::WeiU256& _internal_apparent_value() const;
  ::top::evm_engine::basic::WeiU256* _internal_mutable_apparent_value();
  public:
  void unsafe_arena_set_allocated_apparent_value(
      ::top::evm_engine::basic::WeiU256* apparent_value);
  ::top::evm_engine::basic::WeiU256* unsafe_arena_release_apparent_value();

  // @@protoc_insertion_point(class_scope:top.evm_engine.precompile.ContractContext)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::top::evm_engine::basic::ProtoAddress* address_;
  ::top::evm_engine::basic::ProtoAddress* caller_;
  ::top::evm_engine::basic::WeiU256* apparent_value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_5fprecompile_2eproto;
};
// -------------------------------------------------------------------

class ContractBridgeArgs PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:top.evm_engine.precompile.ContractBridgeArgs) */ {
 public:
  inline ContractBridgeArgs() : ContractBridgeArgs(nullptr) {};
  virtual ~ContractBridgeArgs();

  ContractBridgeArgs(const ContractBridgeArgs& from);
  ContractBridgeArgs(ContractBridgeArgs&& from) noexcept
    : ContractBridgeArgs() {
    *this = ::std::move(from);
  }

  inline ContractBridgeArgs& operator=(const ContractBridgeArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline ContractBridgeArgs& operator=(ContractBridgeArgs&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ContractBridgeArgs& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ContractBridgeArgs* internal_default_instance() {
    return reinterpret_cast<const ContractBridgeArgs*>(
               &_ContractBridgeArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ContractBridgeArgs& a, ContractBridgeArgs& b) {
    a.Swap(&b);
  }
  inline void Swap(ContractBridgeArgs* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ContractBridgeArgs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ContractBridgeArgs* New() const final {
    return CreateMaybeMessage<ContractBridgeArgs>(nullptr);
  }

  ContractBridgeArgs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ContractBridgeArgs>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ContractBridgeArgs& from);
  void MergeFrom(const ContractBridgeArgs& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ContractBridgeArgs* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "top.evm_engine.precompile.ContractBridgeArgs";
  }
  protected:
  explicit ContractBridgeArgs(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_5fprecompile_2eproto);
    return ::descriptor_table_proto_5fprecompile_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInputFieldNumber = 2,
    kContractAddressFieldNumber = 1,
    kContextFieldNumber = 4,
    kTargetGasFieldNumber = 3,
    kIsStaticFieldNumber = 5,
  };
  // bytes input = 2;
  void clear_input();
  const std::string& input() const;
  void set_input(const std::string& value);
  void set_input(std::string&& value);
  void set_input(const char* value);
  void set_input(const void* value, size_t size);
  std::string* mutable_input();
  std::string* release_input();
  void set_allocated_input(std::string* input);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_input();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_input(
      std::string* input);
  private:
  const std::string& _internal_input() const;
  void _internal_set_input(const std::string& value);
  std::string* _internal_mutable_input();
  public:

  // .top.evm_engine.basic.ProtoAddress contract_address = 1;
  bool has_contract_address() const;
  private:
  bool _internal_has_contract_address() const;
  public:
  void clear_contract_address();
  const ::top::evm_engine::basic::ProtoAddress& contract_address() const;
  ::top::evm_engine::basic::ProtoAddress* release_contract_address();
  ::top::evm_engine::basic::ProtoAddress* mutable_contract_address();
  void set_allocated_contract_address(::top::evm_engine::basic::ProtoAddress* contract_address);
  private:
  const ::top::evm_engine::basic::ProtoAddress& _internal_contract_address() const;
  ::top::evm_engine::basic::ProtoAddress* _internal_mutable_contract_address();
  public:
  void unsafe_arena_set_allocated_contract_address(
      ::top::evm_engine::basic::ProtoAddress* contract_address);
  ::top::evm_engine::basic::ProtoAddress* unsafe_arena_release_contract_address();

  // .top.evm_engine.precompile.ContractContext context = 4;
  bool has_context() const;
  private:
  bool _internal_has_context() const;
  public:
  void clear_context();
  const ::top::evm_engine::precompile::ContractContext& context() const;
  ::top::evm_engine::precompile::ContractContext* release_context();
  ::top::evm_engine::precompile::ContractContext* mutable_context();
  void set_allocated_context(::top::evm_engine::precompile::ContractContext* context);
  private:
  const ::top::evm_engine::precompile::ContractContext& _internal_context() const;
  ::top::evm_engine::precompile::ContractContext* _internal_mutable_context();
  public:
  void unsafe_arena_set_allocated_context(
      ::top::evm_engine::precompile::ContractContext* context);
  ::top::evm_engine::precompile::ContractContext* unsafe_arena_release_context();

  // uint64 target_gas = 3;
  void clear_target_gas();
  ::PROTOBUF_NAMESPACE_ID::uint64 target_gas() const;
  void set_target_gas(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_target_gas() const;
  void _internal_set_target_gas(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // bool is_static = 5;
  void clear_is_static();
  bool is_static() const;
  void set_is_static(bool value);
  private:
  bool _internal_is_static() const;
  void _internal_set_is_static(bool value);
  public:

  // @@protoc_insertion_point(class_scope:top.evm_engine.precompile.ContractBridgeArgs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr input_;
  ::top::evm_engine::basic::ProtoAddress* contract_address_;
  ::top::evm_engine::precompile::ContractContext* context_;
  ::PROTOBUF_NAMESPACE_ID::uint64 target_gas_;
  bool is_static_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_5fprecompile_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PrecompileOutput

// uint32 exit_status = 1;
inline void PrecompileOutput::clear_exit_status() {
  exit_status_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PrecompileOutput::_internal_exit_status() const {
  return exit_status_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PrecompileOutput::exit_status() const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.PrecompileOutput.exit_status)
  return _internal_exit_status();
}
inline void PrecompileOutput::_internal_set_exit_status(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  exit_status_ = value;
}
inline void PrecompileOutput::set_exit_status(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_exit_status(value);
  // @@protoc_insertion_point(field_set:top.evm_engine.precompile.PrecompileOutput.exit_status)
}

// uint64 cost = 2;
inline void PrecompileOutput::clear_cost() {
  cost_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PrecompileOutput::_internal_cost() const {
  return cost_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PrecompileOutput::cost() const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.PrecompileOutput.cost)
  return _internal_cost();
}
inline void PrecompileOutput::_internal_set_cost(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  cost_ = value;
}
inline void PrecompileOutput::set_cost(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_cost(value);
  // @@protoc_insertion_point(field_set:top.evm_engine.precompile.PrecompileOutput.cost)
}

// bytes output = 3;
inline void PrecompileOutput::clear_output() {
  output_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PrecompileOutput::output() const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.PrecompileOutput.output)
  return _internal_output();
}
inline void PrecompileOutput::set_output(const std::string& value) {
  _internal_set_output(value);
  // @@protoc_insertion_point(field_set:top.evm_engine.precompile.PrecompileOutput.output)
}
inline std::string* PrecompileOutput::mutable_output() {
  // @@protoc_insertion_point(field_mutable:top.evm_engine.precompile.PrecompileOutput.output)
  return _internal_mutable_output();
}
inline const std::string& PrecompileOutput::_internal_output() const {
  return output_.Get();
}
inline void PrecompileOutput::_internal_set_output(const std::string& value) {
  
  output_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PrecompileOutput::set_output(std::string&& value) {
  
  output_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:top.evm_engine.precompile.PrecompileOutput.output)
}
inline void PrecompileOutput::set_output(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  output_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:top.evm_engine.precompile.PrecompileOutput.output)
}
inline void PrecompileOutput::set_output(const void* value,
    size_t size) {
  
  output_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:top.evm_engine.precompile.PrecompileOutput.output)
}
inline std::string* PrecompileOutput::_internal_mutable_output() {
  
  return output_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PrecompileOutput::release_output() {
  // @@protoc_insertion_point(field_release:top.evm_engine.precompile.PrecompileOutput.output)
  return output_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PrecompileOutput::set_allocated_output(std::string* output) {
  if (output != nullptr) {
    
  } else {
    
  }
  output_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), output,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:top.evm_engine.precompile.PrecompileOutput.output)
}
inline std::string* PrecompileOutput::unsafe_arena_release_output() {
  // @@protoc_insertion_point(field_unsafe_arena_release:top.evm_engine.precompile.PrecompileOutput.output)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return output_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PrecompileOutput::unsafe_arena_set_allocated_output(
    std::string* output) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (output != nullptr) {
    
  } else {
    
  }
  output_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      output, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:top.evm_engine.precompile.PrecompileOutput.output)
}

// repeated .top.evm_engine.basic.ResultLog logs = 4;
inline int PrecompileOutput::_internal_logs_size() const {
  return logs_.size();
}
inline int PrecompileOutput::logs_size() const {
  return _internal_logs_size();
}
inline ::top::evm_engine::basic::ResultLog* PrecompileOutput::mutable_logs(int index) {
  // @@protoc_insertion_point(field_mutable:top.evm_engine.precompile.PrecompileOutput.logs)
  return logs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::top::evm_engine::basic::ResultLog >*
PrecompileOutput::mutable_logs() {
  // @@protoc_insertion_point(field_mutable_list:top.evm_engine.precompile.PrecompileOutput.logs)
  return &logs_;
}
inline const ::top::evm_engine::basic::ResultLog& PrecompileOutput::_internal_logs(int index) const {
  return logs_.Get(index);
}
inline const ::top::evm_engine::basic::ResultLog& PrecompileOutput::logs(int index) const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.PrecompileOutput.logs)
  return _internal_logs(index);
}
inline ::top::evm_engine::basic::ResultLog* PrecompileOutput::_internal_add_logs() {
  return logs_.Add();
}
inline ::top::evm_engine::basic::ResultLog* PrecompileOutput::add_logs() {
  // @@protoc_insertion_point(field_add:top.evm_engine.precompile.PrecompileOutput.logs)
  return _internal_add_logs();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::top::evm_engine::basic::ResultLog >&
PrecompileOutput::logs() const {
  // @@protoc_insertion_point(field_list:top.evm_engine.precompile.PrecompileOutput.logs)
  return logs_;
}

// -------------------------------------------------------------------

// PrecompileFailure

// uint32 fail_status = 1;
inline void PrecompileFailure::clear_fail_status() {
  fail_status_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PrecompileFailure::_internal_fail_status() const {
  return fail_status_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PrecompileFailure::fail_status() const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.PrecompileFailure.fail_status)
  return _internal_fail_status();
}
inline void PrecompileFailure::_internal_set_fail_status(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  fail_status_ = value;
}
inline void PrecompileFailure::set_fail_status(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_fail_status(value);
  // @@protoc_insertion_point(field_set:top.evm_engine.precompile.PrecompileFailure.fail_status)
}

// uint32 minor_status = 2;
inline void PrecompileFailure::clear_minor_status() {
  minor_status_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PrecompileFailure::_internal_minor_status() const {
  return minor_status_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PrecompileFailure::minor_status() const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.PrecompileFailure.minor_status)
  return _internal_minor_status();
}
inline void PrecompileFailure::_internal_set_minor_status(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  minor_status_ = value;
}
inline void PrecompileFailure::set_minor_status(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_minor_status(value);
  // @@protoc_insertion_point(field_set:top.evm_engine.precompile.PrecompileFailure.minor_status)
}

// bytes output = 3;
inline void PrecompileFailure::clear_output() {
  output_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PrecompileFailure::output() const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.PrecompileFailure.output)
  return _internal_output();
}
inline void PrecompileFailure::set_output(const std::string& value) {
  _internal_set_output(value);
  // @@protoc_insertion_point(field_set:top.evm_engine.precompile.PrecompileFailure.output)
}
inline std::string* PrecompileFailure::mutable_output() {
  // @@protoc_insertion_point(field_mutable:top.evm_engine.precompile.PrecompileFailure.output)
  return _internal_mutable_output();
}
inline const std::string& PrecompileFailure::_internal_output() const {
  return output_.Get();
}
inline void PrecompileFailure::_internal_set_output(const std::string& value) {
  
  output_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PrecompileFailure::set_output(std::string&& value) {
  
  output_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:top.evm_engine.precompile.PrecompileFailure.output)
}
inline void PrecompileFailure::set_output(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  output_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:top.evm_engine.precompile.PrecompileFailure.output)
}
inline void PrecompileFailure::set_output(const void* value,
    size_t size) {
  
  output_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:top.evm_engine.precompile.PrecompileFailure.output)
}
inline std::string* PrecompileFailure::_internal_mutable_output() {
  
  return output_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PrecompileFailure::release_output() {
  // @@protoc_insertion_point(field_release:top.evm_engine.precompile.PrecompileFailure.output)
  return output_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PrecompileFailure::set_allocated_output(std::string* output) {
  if (output != nullptr) {
    
  } else {
    
  }
  output_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), output,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:top.evm_engine.precompile.PrecompileFailure.output)
}
inline std::string* PrecompileFailure::unsafe_arena_release_output() {
  // @@protoc_insertion_point(field_unsafe_arena_release:top.evm_engine.precompile.PrecompileFailure.output)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return output_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PrecompileFailure::unsafe_arena_set_allocated_output(
    std::string* output) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (output != nullptr) {
    
  } else {
    
  }
  output_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      output, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:top.evm_engine.precompile.PrecompileFailure.output)
}

// uint64 cost = 4;
inline void PrecompileFailure::clear_cost() {
  cost_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PrecompileFailure::_internal_cost() const {
  return cost_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PrecompileFailure::cost() const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.PrecompileFailure.cost)
  return _internal_cost();
}
inline void PrecompileFailure::_internal_set_cost(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  cost_ = value;
}
inline void PrecompileFailure::set_cost(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_cost(value);
  // @@protoc_insertion_point(field_set:top.evm_engine.precompile.PrecompileFailure.cost)
}

// -------------------------------------------------------------------

// ContractContext

// .top.evm_engine.basic.ProtoAddress address = 1;
inline bool ContractContext::_internal_has_address() const {
  return this != internal_default_instance() && address_ != nullptr;
}
inline bool ContractContext::has_address() const {
  return _internal_has_address();
}
inline const ::top::evm_engine::basic::ProtoAddress& ContractContext::_internal_address() const {
  const ::top::evm_engine::basic::ProtoAddress* p = address_;
  return p != nullptr ? *p : *reinterpret_cast<const ::top::evm_engine::basic::ProtoAddress*>(
      &::top::evm_engine::basic::_ProtoAddress_default_instance_);
}
inline const ::top::evm_engine::basic::ProtoAddress& ContractContext::address() const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.ContractContext.address)
  return _internal_address();
}
inline void ContractContext::unsafe_arena_set_allocated_address(
    ::top::evm_engine::basic::ProtoAddress* address) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(address_);
  }
  address_ = address;
  if (address) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:top.evm_engine.precompile.ContractContext.address)
}
inline ::top::evm_engine::basic::ProtoAddress* ContractContext::release_address() {
  auto temp = unsafe_arena_release_address();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::top::evm_engine::basic::ProtoAddress* ContractContext::unsafe_arena_release_address() {
  // @@protoc_insertion_point(field_release:top.evm_engine.precompile.ContractContext.address)
  
  ::top::evm_engine::basic::ProtoAddress* temp = address_;
  address_ = nullptr;
  return temp;
}
inline ::top::evm_engine::basic::ProtoAddress* ContractContext::_internal_mutable_address() {
  
  if (address_ == nullptr) {
    auto* p = CreateMaybeMessage<::top::evm_engine::basic::ProtoAddress>(GetArena());
    address_ = p;
  }
  return address_;
}
inline ::top::evm_engine::basic::ProtoAddress* ContractContext::mutable_address() {
  // @@protoc_insertion_point(field_mutable:top.evm_engine.precompile.ContractContext.address)
  return _internal_mutable_address();
}
inline void ContractContext::set_allocated_address(::top::evm_engine::basic::ProtoAddress* address) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(address_);
  }
  if (address) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(address)->GetArena();
    if (message_arena != submessage_arena) {
      address = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, address, submessage_arena);
    }
    
  } else {
    
  }
  address_ = address;
  // @@protoc_insertion_point(field_set_allocated:top.evm_engine.precompile.ContractContext.address)
}

// .top.evm_engine.basic.ProtoAddress caller = 2;
inline bool ContractContext::_internal_has_caller() const {
  return this != internal_default_instance() && caller_ != nullptr;
}
inline bool ContractContext::has_caller() const {
  return _internal_has_caller();
}
inline const ::top::evm_engine::basic::ProtoAddress& ContractContext::_internal_caller() const {
  const ::top::evm_engine::basic::ProtoAddress* p = caller_;
  return p != nullptr ? *p : *reinterpret_cast<const ::top::evm_engine::basic::ProtoAddress*>(
      &::top::evm_engine::basic::_ProtoAddress_default_instance_);
}
inline const ::top::evm_engine::basic::ProtoAddress& ContractContext::caller() const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.ContractContext.caller)
  return _internal_caller();
}
inline void ContractContext::unsafe_arena_set_allocated_caller(
    ::top::evm_engine::basic::ProtoAddress* caller) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(caller_);
  }
  caller_ = caller;
  if (caller) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:top.evm_engine.precompile.ContractContext.caller)
}
inline ::top::evm_engine::basic::ProtoAddress* ContractContext::release_caller() {
  auto temp = unsafe_arena_release_caller();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::top::evm_engine::basic::ProtoAddress* ContractContext::unsafe_arena_release_caller() {
  // @@protoc_insertion_point(field_release:top.evm_engine.precompile.ContractContext.caller)
  
  ::top::evm_engine::basic::ProtoAddress* temp = caller_;
  caller_ = nullptr;
  return temp;
}
inline ::top::evm_engine::basic::ProtoAddress* ContractContext::_internal_mutable_caller() {
  
  if (caller_ == nullptr) {
    auto* p = CreateMaybeMessage<::top::evm_engine::basic::ProtoAddress>(GetArena());
    caller_ = p;
  }
  return caller_;
}
inline ::top::evm_engine::basic::ProtoAddress* ContractContext::mutable_caller() {
  // @@protoc_insertion_point(field_mutable:top.evm_engine.precompile.ContractContext.caller)
  return _internal_mutable_caller();
}
inline void ContractContext::set_allocated_caller(::top::evm_engine::basic::ProtoAddress* caller) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(caller_);
  }
  if (caller) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(caller)->GetArena();
    if (message_arena != submessage_arena) {
      caller = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, caller, submessage_arena);
    }
    
  } else {
    
  }
  caller_ = caller;
  // @@protoc_insertion_point(field_set_allocated:top.evm_engine.precompile.ContractContext.caller)
}

// .top.evm_engine.basic.WeiU256 apparent_value = 3;
inline bool ContractContext::_internal_has_apparent_value() const {
  return this != internal_default_instance() && apparent_value_ != nullptr;
}
inline bool ContractContext::has_apparent_value() const {
  return _internal_has_apparent_value();
}
inline const ::top::evm_engine::basic::WeiU256& ContractContext::_internal_apparent_value() const {
  const ::top::evm_engine::basic::WeiU256* p = apparent_value_;
  return p != nullptr ? *p : *reinterpret_cast<const ::top::evm_engine::basic::WeiU256*>(
      &::top::evm_engine::basic::_WeiU256_default_instance_);
}
inline const ::top::evm_engine::basic::WeiU256& ContractContext::apparent_value() const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.ContractContext.apparent_value)
  return _internal_apparent_value();
}
inline void ContractContext::unsafe_arena_set_allocated_apparent_value(
    ::top::evm_engine::basic::WeiU256* apparent_value) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(apparent_value_);
  }
  apparent_value_ = apparent_value;
  if (apparent_value) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:top.evm_engine.precompile.ContractContext.apparent_value)
}
inline ::top::evm_engine::basic::WeiU256* ContractContext::release_apparent_value() {
  auto temp = unsafe_arena_release_apparent_value();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::top::evm_engine::basic::WeiU256* ContractContext::unsafe_arena_release_apparent_value() {
  // @@protoc_insertion_point(field_release:top.evm_engine.precompile.ContractContext.apparent_value)
  
  ::top::evm_engine::basic::WeiU256* temp = apparent_value_;
  apparent_value_ = nullptr;
  return temp;
}
inline ::top::evm_engine::basic::WeiU256* ContractContext::_internal_mutable_apparent_value() {
  
  if (apparent_value_ == nullptr) {
    auto* p = CreateMaybeMessage<::top::evm_engine::basic::WeiU256>(GetArena());
    apparent_value_ = p;
  }
  return apparent_value_;
}
inline ::top::evm_engine::basic::WeiU256* ContractContext::mutable_apparent_value() {
  // @@protoc_insertion_point(field_mutable:top.evm_engine.precompile.ContractContext.apparent_value)
  return _internal_mutable_apparent_value();
}
inline void ContractContext::set_allocated_apparent_value(::top::evm_engine::basic::WeiU256* apparent_value) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(apparent_value_);
  }
  if (apparent_value) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(apparent_value)->GetArena();
    if (message_arena != submessage_arena) {
      apparent_value = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, apparent_value, submessage_arena);
    }
    
  } else {
    
  }
  apparent_value_ = apparent_value;
  // @@protoc_insertion_point(field_set_allocated:top.evm_engine.precompile.ContractContext.apparent_value)
}

// -------------------------------------------------------------------

// ContractBridgeArgs

// .top.evm_engine.basic.ProtoAddress contract_address = 1;
inline bool ContractBridgeArgs::_internal_has_contract_address() const {
  return this != internal_default_instance() && contract_address_ != nullptr;
}
inline bool ContractBridgeArgs::has_contract_address() const {
  return _internal_has_contract_address();
}
inline const ::top::evm_engine::basic::ProtoAddress& ContractBridgeArgs::_internal_contract_address() const {
  const ::top::evm_engine::basic::ProtoAddress* p = contract_address_;
  return p != nullptr ? *p : *reinterpret_cast<const ::top::evm_engine::basic::ProtoAddress*>(
      &::top::evm_engine::basic::_ProtoAddress_default_instance_);
}
inline const ::top::evm_engine::basic::ProtoAddress& ContractBridgeArgs::contract_address() const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.ContractBridgeArgs.contract_address)
  return _internal_contract_address();
}
inline void ContractBridgeArgs::unsafe_arena_set_allocated_contract_address(
    ::top::evm_engine::basic::ProtoAddress* contract_address) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(contract_address_);
  }
  contract_address_ = contract_address;
  if (contract_address) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:top.evm_engine.precompile.ContractBridgeArgs.contract_address)
}
inline ::top::evm_engine::basic::ProtoAddress* ContractBridgeArgs::release_contract_address() {
  auto temp = unsafe_arena_release_contract_address();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::top::evm_engine::basic::ProtoAddress* ContractBridgeArgs::unsafe_arena_release_contract_address() {
  // @@protoc_insertion_point(field_release:top.evm_engine.precompile.ContractBridgeArgs.contract_address)
  
  ::top::evm_engine::basic::ProtoAddress* temp = contract_address_;
  contract_address_ = nullptr;
  return temp;
}
inline ::top::evm_engine::basic::ProtoAddress* ContractBridgeArgs::_internal_mutable_contract_address() {
  
  if (contract_address_ == nullptr) {
    auto* p = CreateMaybeMessage<::top::evm_engine::basic::ProtoAddress>(GetArena());
    contract_address_ = p;
  }
  return contract_address_;
}
inline ::top::evm_engine::basic::ProtoAddress* ContractBridgeArgs::mutable_contract_address() {
  // @@protoc_insertion_point(field_mutable:top.evm_engine.precompile.ContractBridgeArgs.contract_address)
  return _internal_mutable_contract_address();
}
inline void ContractBridgeArgs::set_allocated_contract_address(::top::evm_engine::basic::ProtoAddress* contract_address) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(contract_address_);
  }
  if (contract_address) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(contract_address)->GetArena();
    if (message_arena != submessage_arena) {
      contract_address = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, contract_address, submessage_arena);
    }
    
  } else {
    
  }
  contract_address_ = contract_address;
  // @@protoc_insertion_point(field_set_allocated:top.evm_engine.precompile.ContractBridgeArgs.contract_address)
}

// bytes input = 2;
inline void ContractBridgeArgs::clear_input() {
  input_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ContractBridgeArgs::input() const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.ContractBridgeArgs.input)
  return _internal_input();
}
inline void ContractBridgeArgs::set_input(const std::string& value) {
  _internal_set_input(value);
  // @@protoc_insertion_point(field_set:top.evm_engine.precompile.ContractBridgeArgs.input)
}
inline std::string* ContractBridgeArgs::mutable_input() {
  // @@protoc_insertion_point(field_mutable:top.evm_engine.precompile.ContractBridgeArgs.input)
  return _internal_mutable_input();
}
inline const std::string& ContractBridgeArgs::_internal_input() const {
  return input_.Get();
}
inline void ContractBridgeArgs::_internal_set_input(const std::string& value) {
  
  input_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ContractBridgeArgs::set_input(std::string&& value) {
  
  input_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:top.evm_engine.precompile.ContractBridgeArgs.input)
}
inline void ContractBridgeArgs::set_input(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  input_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:top.evm_engine.precompile.ContractBridgeArgs.input)
}
inline void ContractBridgeArgs::set_input(const void* value,
    size_t size) {
  
  input_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:top.evm_engine.precompile.ContractBridgeArgs.input)
}
inline std::string* ContractBridgeArgs::_internal_mutable_input() {
  
  return input_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ContractBridgeArgs::release_input() {
  // @@protoc_insertion_point(field_release:top.evm_engine.precompile.ContractBridgeArgs.input)
  return input_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ContractBridgeArgs::set_allocated_input(std::string* input) {
  if (input != nullptr) {
    
  } else {
    
  }
  input_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), input,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:top.evm_engine.precompile.ContractBridgeArgs.input)
}
inline std::string* ContractBridgeArgs::unsafe_arena_release_input() {
  // @@protoc_insertion_point(field_unsafe_arena_release:top.evm_engine.precompile.ContractBridgeArgs.input)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return input_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ContractBridgeArgs::unsafe_arena_set_allocated_input(
    std::string* input) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (input != nullptr) {
    
  } else {
    
  }
  input_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      input, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:top.evm_engine.precompile.ContractBridgeArgs.input)
}

// uint64 target_gas = 3;
inline void ContractBridgeArgs::clear_target_gas() {
  target_gas_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ContractBridgeArgs::_internal_target_gas() const {
  return target_gas_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ContractBridgeArgs::target_gas() const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.ContractBridgeArgs.target_gas)
  return _internal_target_gas();
}
inline void ContractBridgeArgs::_internal_set_target_gas(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  target_gas_ = value;
}
inline void ContractBridgeArgs::set_target_gas(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_target_gas(value);
  // @@protoc_insertion_point(field_set:top.evm_engine.precompile.ContractBridgeArgs.target_gas)
}

// .top.evm_engine.precompile.ContractContext context = 4;
inline bool ContractBridgeArgs::_internal_has_context() const {
  return this != internal_default_instance() && context_ != nullptr;
}
inline bool ContractBridgeArgs::has_context() const {
  return _internal_has_context();
}
inline void ContractBridgeArgs::clear_context() {
  if (GetArena() == nullptr && context_ != nullptr) {
    delete context_;
  }
  context_ = nullptr;
}
inline const ::top::evm_engine::precompile::ContractContext& ContractBridgeArgs::_internal_context() const {
  const ::top::evm_engine::precompile::ContractContext* p = context_;
  return p != nullptr ? *p : *reinterpret_cast<const ::top::evm_engine::precompile::ContractContext*>(
      &::top::evm_engine::precompile::_ContractContext_default_instance_);
}
inline const ::top::evm_engine::precompile::ContractContext& ContractBridgeArgs::context() const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.ContractBridgeArgs.context)
  return _internal_context();
}
inline void ContractBridgeArgs::unsafe_arena_set_allocated_context(
    ::top::evm_engine::precompile::ContractContext* context) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(context_);
  }
  context_ = context;
  if (context) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:top.evm_engine.precompile.ContractBridgeArgs.context)
}
inline ::top::evm_engine::precompile::ContractContext* ContractBridgeArgs::release_context() {
  auto temp = unsafe_arena_release_context();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::top::evm_engine::precompile::ContractContext* ContractBridgeArgs::unsafe_arena_release_context() {
  // @@protoc_insertion_point(field_release:top.evm_engine.precompile.ContractBridgeArgs.context)
  
  ::top::evm_engine::precompile::ContractContext* temp = context_;
  context_ = nullptr;
  return temp;
}
inline ::top::evm_engine::precompile::ContractContext* ContractBridgeArgs::_internal_mutable_context() {
  
  if (context_ == nullptr) {
    auto* p = CreateMaybeMessage<::top::evm_engine::precompile::ContractContext>(GetArena());
    context_ = p;
  }
  return context_;
}
inline ::top::evm_engine::precompile::ContractContext* ContractBridgeArgs::mutable_context() {
  // @@protoc_insertion_point(field_mutable:top.evm_engine.precompile.ContractBridgeArgs.context)
  return _internal_mutable_context();
}
inline void ContractBridgeArgs::set_allocated_context(::top::evm_engine::precompile::ContractContext* context) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete context_;
  }
  if (context) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(context);
    if (message_arena != submessage_arena) {
      context = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, context, submessage_arena);
    }
    
  } else {
    
  }
  context_ = context;
  // @@protoc_insertion_point(field_set_allocated:top.evm_engine.precompile.ContractBridgeArgs.context)
}

// bool is_static = 5;
inline void ContractBridgeArgs::clear_is_static() {
  is_static_ = false;
}
inline bool ContractBridgeArgs::_internal_is_static() const {
  return is_static_;
}
inline bool ContractBridgeArgs::is_static() const {
  // @@protoc_insertion_point(field_get:top.evm_engine.precompile.ContractBridgeArgs.is_static)
  return _internal_is_static();
}
inline void ContractBridgeArgs::_internal_set_is_static(bool value) {
  
  is_static_ = value;
}
inline void ContractBridgeArgs::set_is_static(bool value) {
  _internal_set_is_static(value);
  // @@protoc_insertion_point(field_set:top.evm_engine.precompile.ContractBridgeArgs.is_static)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace precompile
}  // namespace evm_engine
}  // namespace top

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_5fprecompile_2eproto
