// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elect_net.proto

#ifndef PROTOBUF_INCLUDED_elect_5fnet_2eproto
#define PROTOBUF_INCLUDED_elect_5fnet_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_elect_5fnet_2eproto 

namespace protobuf_elect_5fnet_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_elect_5fnet_2eproto
namespace top {
namespace elect {
namespace protobuf {
class VhostMessage;
class VhostMessageDefaultTypeInternal;
extern VhostMessageDefaultTypeInternal _VhostMessage_default_instance_;
}  // namespace protobuf
}  // namespace elect
}  // namespace top
namespace google {
namespace protobuf {
template<> ::top::elect::protobuf::VhostMessage* Arena::CreateMaybeMessage<::top::elect::protobuf::VhostMessage>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace top {
namespace elect {
namespace protobuf {

// ===================================================================

class VhostMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:top.elect.protobuf.VhostMessage) */ {
 public:
  VhostMessage();
  virtual ~VhostMessage();

  VhostMessage(const VhostMessage& from);

  inline VhostMessage& operator=(const VhostMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  VhostMessage(VhostMessage&& from) noexcept
    : VhostMessage() {
    *this = ::std::move(from);
  }

  inline VhostMessage& operator=(VhostMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VhostMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VhostMessage* internal_default_instance() {
    return reinterpret_cast<const VhostMessage*>(
               &_VhostMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(VhostMessage* other);
  friend void swap(VhostMessage& a, VhostMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline VhostMessage* New() const final {
    return CreateMaybeMessage<VhostMessage>(NULL);
  }

  VhostMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<VhostMessage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const VhostMessage& from);
  void MergeFrom(const VhostMessage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VhostMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes data = 2;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 2;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // optional bytes node_id = 4;
  bool has_node_id() const;
  void clear_node_id();
  static const int kNodeIdFieldNumber = 4;
  const ::std::string& node_id() const;
  void set_node_id(const ::std::string& value);
  #if LANG_CXX11
  void set_node_id(::std::string&& value);
  #endif
  void set_node_id(const char* value);
  void set_node_id(const void* value, size_t size);
  ::std::string* mutable_node_id();
  ::std::string* release_node_id();
  void set_allocated_node_id(::std::string* node_id);

  // optional uint32 type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::google::protobuf::uint32 type() const;
  void set_type(::google::protobuf::uint32 value);

  // optional uint32 cb_type = 3;
  bool has_cb_type() const;
  void clear_cb_type();
  static const int kCbTypeFieldNumber = 3;
  ::google::protobuf::uint32 cb_type() const;
  void set_cb_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:top.elect.protobuf.VhostMessage)
 private:
  void set_has_type();
  void clear_has_type();
  void set_has_data();
  void clear_has_data();
  void set_has_cb_type();
  void clear_has_cb_type();
  void set_has_node_id();
  void clear_has_node_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::internal::ArenaStringPtr node_id_;
  ::google::protobuf::uint32 type_;
  ::google::protobuf::uint32 cb_type_;
  friend struct ::protobuf_elect_5fnet_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VhostMessage

// optional uint32 type = 1;
inline bool VhostMessage::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void VhostMessage::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void VhostMessage::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void VhostMessage::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 VhostMessage::type() const {
  // @@protoc_insertion_point(field_get:top.elect.protobuf.VhostMessage.type)
  return type_;
}
inline void VhostMessage::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:top.elect.protobuf.VhostMessage.type)
}

// optional bytes data = 2;
inline bool VhostMessage::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void VhostMessage::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void VhostMessage::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void VhostMessage::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data();
}
inline const ::std::string& VhostMessage::data() const {
  // @@protoc_insertion_point(field_get:top.elect.protobuf.VhostMessage.data)
  return data_.GetNoArena();
}
inline void VhostMessage::set_data(const ::std::string& value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:top.elect.protobuf.VhostMessage.data)
}
#if LANG_CXX11
inline void VhostMessage::set_data(::std::string&& value) {
  set_has_data();
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:top.elect.protobuf.VhostMessage.data)
}
#endif
inline void VhostMessage::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:top.elect.protobuf.VhostMessage.data)
}
inline void VhostMessage::set_data(const void* value, size_t size) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:top.elect.protobuf.VhostMessage.data)
}
inline ::std::string* VhostMessage::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:top.elect.protobuf.VhostMessage.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VhostMessage::release_data() {
  // @@protoc_insertion_point(field_release:top.elect.protobuf.VhostMessage.data)
  if (!has_data()) {
    return NULL;
  }
  clear_has_data();
  return data_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VhostMessage::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:top.elect.protobuf.VhostMessage.data)
}

// optional uint32 cb_type = 3;
inline bool VhostMessage::has_cb_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void VhostMessage::set_has_cb_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void VhostMessage::clear_has_cb_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void VhostMessage::clear_cb_type() {
  cb_type_ = 0u;
  clear_has_cb_type();
}
inline ::google::protobuf::uint32 VhostMessage::cb_type() const {
  // @@protoc_insertion_point(field_get:top.elect.protobuf.VhostMessage.cb_type)
  return cb_type_;
}
inline void VhostMessage::set_cb_type(::google::protobuf::uint32 value) {
  set_has_cb_type();
  cb_type_ = value;
  // @@protoc_insertion_point(field_set:top.elect.protobuf.VhostMessage.cb_type)
}

// optional bytes node_id = 4;
inline bool VhostMessage::has_node_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void VhostMessage::set_has_node_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void VhostMessage::clear_has_node_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void VhostMessage::clear_node_id() {
  node_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_node_id();
}
inline const ::std::string& VhostMessage::node_id() const {
  // @@protoc_insertion_point(field_get:top.elect.protobuf.VhostMessage.node_id)
  return node_id_.GetNoArena();
}
inline void VhostMessage::set_node_id(const ::std::string& value) {
  set_has_node_id();
  node_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:top.elect.protobuf.VhostMessage.node_id)
}
#if LANG_CXX11
inline void VhostMessage::set_node_id(::std::string&& value) {
  set_has_node_id();
  node_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:top.elect.protobuf.VhostMessage.node_id)
}
#endif
inline void VhostMessage::set_node_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_node_id();
  node_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:top.elect.protobuf.VhostMessage.node_id)
}
inline void VhostMessage::set_node_id(const void* value, size_t size) {
  set_has_node_id();
  node_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:top.elect.protobuf.VhostMessage.node_id)
}
inline ::std::string* VhostMessage::mutable_node_id() {
  set_has_node_id();
  // @@protoc_insertion_point(field_mutable:top.elect.protobuf.VhostMessage.node_id)
  return node_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VhostMessage::release_node_id() {
  // @@protoc_insertion_point(field_release:top.elect.protobuf.VhostMessage.node_id)
  if (!has_node_id()) {
    return NULL;
  }
  clear_has_node_id();
  return node_id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VhostMessage::set_allocated_node_id(::std::string* node_id) {
  if (node_id != NULL) {
    set_has_node_id();
  } else {
    clear_has_node_id();
  }
  node_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), node_id);
  // @@protoc_insertion_point(field_set_allocated:top.elect.protobuf.VhostMessage.node_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace elect
}  // namespace top

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_elect_5fnet_2eproto
