[package]
name = "xwasmer_engine"
version = "0.1.0"
authors = []
edition = "2021"
description = ""
documentation = ""
readme = false
homepage = ""
repository = ""
license = ""
publish = false
autobenches = false
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = { version = "2.3.0", default-features = false, features = [
    "cranelift",
    "universal",
    "singlepass",
] }
wasmer-wasi = "2.3.0"
wasmer-middlewares = "2.3.0"
anyhow = "1.0"
thiserror = "1.0"
libc = "0.2.9"
loupe = "0.1.3"


[dev-dependencies]
wat = "1.0"

[lib]
crate_type = ["rlib", "staticlib"]

[features]
build_as_xtop_lib = []
