#include "xdata/xnative_contract_address.h"

NS_BEG1(top)

common::xaccount_address_t const black_hole_system_address{black_hole_addr};
common::xaccount_address_t const genesis_root_system_address{genesis_root_addr_main_chain};
common::xaccount_address_t const timer_system_address{sys_contract_beacon_timer_addr};
common::xaccount_address_t const drand_system_address{sys_drand_addr};

common::xaccount_address_t const rec_registration_contract_address{sys_contract_rec_registration_addr};
common::xaccount_address_t const rec_elect_edge_contract_address{sys_contract_rec_elect_edge_addr};
common::xaccount_address_t const rec_elect_archive_contract_address{sys_contract_rec_elect_archive_addr};
common::xaccount_address_t const rec_elect_exchange_contract_address{sys_contract_rec_elect_exchange_addr};
common::xaccount_address_t const rec_elect_fullnode_contract_address{sys_contract_rec_elect_fullnode_addr};
common::xaccount_address_t const rec_elect_rec_contract_address{sys_contract_rec_elect_rec_addr};
common::xaccount_address_t const rec_elect_zec_contract_address{sys_contract_rec_elect_zec_addr};
common::xaccount_address_t const rec_tcc_contract_address{sys_contract_rec_tcc_addr};
common::xaccount_address_t const rec_standby_pool_contract_address{sys_contract_rec_standby_pool_addr};

common::xaccount_address_t const zec_workload_contract_address{sys_contract_zec_workload_addr};
common::xaccount_address_t const zec_vote_contract_address{sys_contract_zec_vote_addr};
common::xaccount_address_t const zec_reward_contract_address{sys_contract_zec_reward_addr};
common::xaccount_address_t const zec_slash_info_contract_address{sys_contract_zec_slash_info_addr};
common::xaccount_address_t const zec_elect_consensus_contract_address{sys_contract_zec_elect_consensus_addr};
common::xaccount_address_t const zec_standby_pool_contract_address{sys_contract_zec_standby_pool_addr};
common::xaccount_address_t const zec_group_assoc_contract_address{sys_contract_zec_group_assoc_addr};
common::xaccount_address_t const zec_elect_eth_contract_address{sys_contract_zec_elect_eth_addr};
common::xaccount_address_t const zec_elect_relay_contract_address{sys_contract_zec_elect_relay_addr};

common::xaccount_address_t const sharding_vote_contract_address{sys_contract_sharding_vote_addr};
common::xaccount_address_t const sharding_reward_claiming_contract_address{sys_contract_sharding_reward_claiming_addr};
common::xaccount_address_t const sharding_statistic_info_contract_address{sys_contract_sharding_statistic_info_addr};
common::xaccount_address_t const sharding_fork_info_contract_address{sys_contract_sharding_fork_info_addr};

common::xaccount_address_t const eth_fork_info_contract_address{sys_contract_eth_fork_info_addr};
common::xaccount_address_t const eth_statistic_info_contract_address{sys_contract_eth_table_statistic_info_addr};
common::xaccount_address_t const eth_table_cross_chain_txs_collection_contract_address{sys_contract_eth_table_cross_chain_txs_collection_addr};

common::xaccount_address_t const eth_zero_address{"T600040000000000000000000000000000000000000000"};

common::xaccount_address_t const rec_table_address{sys_contract_beacon_table_block_addr};
common::xaccount_address_t const zec_table_address{sys_contract_zec_table_block_addr};
common::xaccount_address_t const sharding_table_address{sys_contract_sharding_table_block_addr};
common::xaccount_address_t const eth_table_address{sys_contract_eth_table_block_addr};
common::xaccount_base_address_t const relay_table_base_address{common::xaccount_base_address_t::build_from(sys_contract_relay_table_block_base_addr)};
common::xaccount_address_t const relay_table_address{sys_contract_relay_table_block_addr};

// common::xaccount_address_t const evm_erc20_contract_address{"T60004ff00000000000000000000000000000000000001"};
common::xaccount_address_t const evm_eth_bridge_contract_address{"T60004ff00000000000000000000000000000000000002"};
common::xaccount_address_t const evm_bsc_client_contract_address{"T60004ff00000000000000000000000000000000000003"};
common::xaccount_address_t const evm_heco_client_contract_address{"T60004ff00000000000000000000000000000000000004"};
common::xaccount_address_t const evm_eth2_client_contract_address{"T60004ff00000000000000000000000000000000000009"};
common::xaccount_address_t const evm_top_contract_address{"T60004ff00000000000000000000000000000000000005"};
common::xaccount_address_t const evm_eth_contract_address{"T60004ff00000000000000000000000000000000000006"};
common::xaccount_address_t const evm_usdt_contract_address{"T60004ff00000000000000000000000000000000000007"};
common::xaccount_address_t const evm_usdc_contract_address{"T60004ff00000000000000000000000000000000000008"};

common::xaccount_address_t const relay_make_block_contract_address{sys_contract_relay_make_block_addr};

NS_END1
