# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ dev/fast_sync_develop ]
  pull_request:
    branches: [ dev/fast_sync_develop ]

jobs:
  build:
    if: github.repository_owner == 'telosprotocol' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize' || github.event_name == 'pushed')
    # if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event_name == 'push'
    runs-on: [self-hosted, Linux, X64]
    
    # for ci telos only
    steps:
      - name: Print event
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build XTOP DEBUG
        run: |
          bash .github/scripts/build_xtop.sh "test build_ci"

      - name: TEST XTOP AllInOne
        env:
          RUN_NUM: ${{ github.run_number }}
        run: |
          bash .github/scripts/test_xtop_allinone.sh "$RUN_NUM"
